### PR TITLE
fix: update vault available

### LINKED ISSUE #2093: [bug]: UI does not show proper fees available for withdraw
### Contact Details

Tritium

### What happened?

Right now the UI reports the tokens available for withdraw as those available in the stgrategy.  I think.

In fact, here is how withdraw availability works.

Unlocked tokens could be in the Vault, The stratgey, or in the locker(there should be functions in the strategy to see this)

The tokens available for withdraw display should reflect the sum all tokens available in the locker, the strat or the vault.

### Version

current

### What browsers are you seeing the problem on?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by axejintao**
fixes #2093

### CODE REVIEW

File: src/mobx/stores/LockedDepositsStore.ts [hunk 1]
```diff
@@ -56,23 +55,38 @@ class LockedDepositsStore {
...
 			await Promise.all([
-				await tokenContract.balanceOf(vaultAddress),
-				await tokenContract.balanceOf(strategyAddress),
+				await tokenContract.balanceOf(vault.vaultToken),
+				await tokenContract.balanceOf(vault.strategy.address),
 				await voteLockedDepositContract.lockedBalanceOf(vaultAddress),
 				await voteLockedDepositContract.balanceOf(vaultAddress),
 			]);
 
+		console.log({
```
Comment (eliobricenov) [inline src/mobx/stores/LockedDepositsStore.ts:76]: Do we need this log?

Comment (axejintao) [reply src/mobx/stores/LockedDepositsStore.ts:76]: no
